import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import {
  Roboto,
  Kumbh_Sans,
  Poppins,
  Figtree,
  Inter,
  DM_Sans,
} from "next/font/google";

import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
});
const kumbh_sans = Kumbh_Sans({
  subsets: ["latin"],
  variable: "--font-kumbh_sans",
  display: "swap",
});
const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
});
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  weight: ["100", "300", "400", "500", "700", "900"],
});

const dMsans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dMsans",
  display: "swap",
});

export const metadata = {
  title: "Discount Me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ToastContainer />
      <body
        className={`${inter.variable} ${kumbh_sans.variable} ${figtree.variable} ${poppins.variable} ${roboto.variable} ${dMsans.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
